# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhDP1dphgP2nq7FpCMROjkt6LxlZlAnb
"""

names =["Kagetera","John","Peter","Alex","Cloude"]
names.append("kagabo")
names.append("university of kigali")
names.sort()
print(names)

